// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDdBFNHMevQZrJ68op3GnWl9q4quHdXExk',
    appId: '1:19874969586:web:2d8e04f0d7998425255d6b',
    messagingSenderId: '19874969586',
    projectId: 'tracky-86204',
    authDomain: 'tracky-86204.firebaseapp.com',
    storageBucket: 'tracky-86204.firebasestorage.app',
    measurementId: 'G-CKZFFZSSJE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBr3NBa1lkSP3JR_WrsVTL2iyt36L1U_kI',
    appId: '1:19874969586:android:4cfc6062b74485a0255d6b',
    messagingSenderId: '19874969586',
    projectId: 'tracky-86204',
    storageBucket: 'tracky-86204.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCVObtlMQFcM15EG8xRylkjMlj1swycFXY',
    appId: '1:19874969586:ios:8dc8feee6256d575255d6b',
    messagingSenderId: '19874969586',
    projectId: 'tracky-86204',
    storageBucket: 'tracky-86204.firebasestorage.app',
    iosBundleId: 'com.example.trackyFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCVObtlMQFcM15EG8xRylkjMlj1swycFXY',
    appId: '1:19874969586:ios:8dc8feee6256d575255d6b',
    messagingSenderId: '19874969586',
    projectId: 'tracky-86204',
    storageBucket: 'tracky-86204.firebasestorage.app',
    iosBundleId: 'com.example.trackyFlutter',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDdBFNHMevQZrJ68op3GnWl9q4quHdXExk',
    appId: '1:19874969586:web:7713bfccf88d4bd5255d6b',
    messagingSenderId: '19874969586',
    projectId: 'tracky-86204',
    authDomain: 'tracky-86204.firebaseapp.com',
    storageBucket: 'tracky-86204.firebasestorage.app',
    measurementId: 'G-Z8WH42P5PP',
  );
}
